version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
     - image: cimg/go:1.21
    branches:
      only:
        - master
    steps:
      - checkout
      - setup_remote_docker

      - run: echo 'export DOCKER_REPO="$(if [ ${CIRCLE_PROJECT_USERNAME} == 'Securing-DevOps' ]; then echo securingdevops; else echo $DOCKER_USER; fi)"' >> $BASH_ENV
      - run: echo 'export GOFLAGS=-mod=mod' >> $BASH_ENV

      - run:
          name: Build application container
          command: |
            CGO_ENABLED=1 go build -o bin/invoicer --ldflags '-extldflags "-static"' -tags netgo .;
            docker build -t ${DOCKER_REPO}/${CIRCLE_PROJECT_REPONAME} .;

      - run:
          name: Create Docker network
          command: docker network create test-net

      - run:
          name: Run application in background
          command: |
            docker run --name invoicer-app --network test-net -d ${DOCKER_REPO}/${CIRCLE_PROJECT_REPONAME}

      - run:
          name: ZAP baseline test of application
          # Only fail on error code 1, which indicates at least one FAIL was found.
          # error codes 2 & 3 indicate WARN or other, and should not break the run
          command: |
            (
            docker pull ghcr.io/zaproxy/zaproxy:latest && \
            docker run --network test-net -v $(pwd):/zap/wrk/:rw -u root -t ghcr.io/zaproxy/zaproxy:latest zap-baseline.py \
                -u https://raw.githubusercontent.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/master/zap-baseline.conf \
                -t http://invoicer-app:8080/ || \
            if [ $? -ne 1 ]; then exit 0; else exit 1; fi;
            )

      - run:
          name: Verify dependencies
          command: go mod tidy && git diff --quiet go.mod

      - deploy:
          # Push application container to dockerhub
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
                docker login -u ${DOCKER_USER} -p ${DOCKER_PASS};
                echo ${DOCKER_USER}/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_TAG};
                CGO_ENABLED=1 go build -o bin/invoicer --ldflags '-extldflags "-static"' -tags netgo .;
                docker build -t ${DOCKER_REPO}/${CIRCLE_PROJECT_REPONAME} .;
                docker images --no-trunc | awk '/^app/ {print $3}' | sudo tee $CIRCLE_ARTIFACTS/docker-image-shasum256.txt;
                docker push ${DOCKER_REPO}/${CIRCLE_PROJECT_REPONAME};
            fi
